spring.application.name=SmartCity

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/greencity}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:damjan}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:10000}
